#
# Copyright (c) 2025-2025 Ricardo do Canto
#
# This file is part of the EnduranceTrio Tracker project.
#
# Licensed under the Functional Software License (FSL), Version 1.1, ALv2 Future License
# (the "License");
#
# You may not use this file except in compliance with the License. You may obtain a copy
# of the License at https://fsl.software/
#
# THE SOFTWARE IS PROVIDED "AS IS" AND WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING WITHOUT LIMITATION WARRANTIES OF FITNESS FOR A PARTICULAR
# PURPOSE, MERCHANTABILITY, TITLE OR NON-INFRINGEMENT.
#
# IN NO EVENT WILL WE HAVE ANY LIABILITY TO YOU ARISING OUT OF OR RELATED TO THE
# SOFTWARE, INCLUDING INDIRECT, SPECIAL, INCIDENTAL OR CONSEQUENTIAL DAMAGES,
# EVEN IF WE HAVE BEEN INFORMED OF THEIR POSSIBILITY IN ADVANCE.
#

#
# This file is intended to serve as a template for the application-secrets.yaml file that needs
# to contain sensitive information such as database credentials. Users should copy this file
# and rename it to application-secrets.yaml, and fill in their actual secrets.
#
# The file application-secrets.yaml is excluded from version control to protect sensitive data
# and should never be commited
#
# Usage Instructions:
#
# Step 1: Copy this file to application-secrets.yaml, using the command:
#
#         cp template-secrets.yaml application-secrets.yaml
#
# Step 2: Fill in the actual database username and password, replacing {USER} and {PASSWORD}
#         with the correct values.
#
# Step 3: Ensure that application-secrets.yaml is listed in your .gitignore file
#         to prevent it from being committed.
#
spring:
  datasource:
    username: {USER}
    password: {PASSWORD}
